name: NPM release

# Hooks
on:
  release:
    types: [created]

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        run: npm publish
